name: CICD Pipeline

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  model-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y zip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest awscli

      - name: Run pipeline
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-north-1
        run: |
          dvc repro

      - name: Push DVC tracked data to remote
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-north-1
        run: |
          dvc push

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push changes
        if: ${{ github.actor != 'github-actions[bot]' }}
        run: |
          git add .
          git commit -m "Automated commit of DVC outputs and updated files" || echo "No changes to commit"
          git push origin master

      - name: Run model loading test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-north-1
        run: |
          pytest scripts/test_load_model.py

      - name: Run model signature test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-north-1
        run: |
          pytest scripts/test_model_signature.py

      - name: Run model performance test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-north-1
        run: |
          pytest scripts/test_model_performance.py

      - name: Promote model to production
        if: success()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-north-1
        run: |
          python scripts/promote_model.py

      - name: Login to AWS ECR
        if: success()
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region eu-north-1
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 985539756441.dkr.ecr.eu-north-1.amazonaws.com

      - name: Build Docker image
        if: success()
        run: |
          docker build -t yt-chrome-plugin .

      - name: Tag Docker image
        if: success()
        run: |
          docker tag yt-chrome-plugin:latest 985539756441.dkr.ecr.eu-north-1.amazonaws.com/yt-chrome-plugin:latest

      - name: Push Docker image to AWS ECR
        if: success()
        run: |
          docker push 985539756441.dkr.ecr.eu-north-1.amazonaws.com/yt-chrome-plugin:latest

      - name: Zip files for deployment
        if: success()
        run: |
          zip -r deployment.zip appspec.yml deploy/scripts/install_dependencies.sh deploy/scripts/start_docker.sh

      - name: Upload ZIP to S3
        if: success()
        run: |
          aws s3 cp deployment.zip s3://adinath-mlfow-bucket/deployment.zip --region eu-north-1

      - name: Deploy to AWS CodeDeploy
        if: success()
        run: |
          aws deploy create-deployment \
            --application-name YTChromePlugin \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --deployment-group-name YTChromePluginDeploymentGroup \
            --s3-location bucket=campusxcodedeploybucket,key=deployment.zip,bundleType=zip \
            --file-exists-behavior OVERWRITE \
            --region eu-north-1